# new-issue-welcome bot:
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Someone will look over this issue shortly, hang tight for now!

# new-pr-welcome bot:
newPRWelcomeComment: >
  Thanks for opening this pull request! A project maintainer will review your contribution shortly.

# first-pr-merge bot:
firstPRMergeComment: >
  Congrats on getting your first pull request merged! You are now a contributor 😎!
