container:
  image: python:latest

Build_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: python3 -m pip install --upgrade setuptools wheel twine
  Build_script: python3 setup.py sdist bdist_wheel

MarkdownTests_task:
  container:
    image: node:latest
  InstallLinter_script: npm install -g markdownlint-cli
  InstallLinkChecker_script: npm install -g markdown-link-check@3.7.2
  MarkdownLint_script:
    - markdownlint --config=.markdownlint.yml *.md
    - markdownlint --config=.markdownlint.yml .github/*.md
    - markdownlint --config=.markdownlint.yml extras/*.md
  LinkCheck_script: find . -name \*.md -exec markdown-link-check {} \;

CodeTests_task:
  depends_on:
    - Build
  InstallTestDependencies_script:
    - cd $CIRRUS_WORKING_DIR/requirements/
    - python3 -m pip install -r test.txt
    - python3 -m pip install --upgrade area4
  Test_script:
    - cd $CIRRUS_WORKING_DIR
    - python3 test-code.py
