test_task:
  container:
    image: python:latest
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: python3 -m pip install --upgrade pip==9.0.1 setuptools wheel twine
  test_script: python3 setup.py sdist bdist_wheel && rm -r build/ && rm -r area4.egg-info/ && ls dist/ && pip install --upgrade area4

spellcheck_task:
  container:
    image: node:latest
    node_modules_cache:
      folder: node_modules
      fingerprint_script: cat requirements.txt
      populate_script: sudo npm install -g markdown-spellcheck@0.11.0
    script: mdspell '**/*.md' --ignore-numbers --ignore-acronyms --report --en-us;
    
