Tests_task:
  container:
    image: python:latest
  only_if: $CIRRUS_BRANCH != 'python-2-supported'
  auto_cancellation: $CIRRUS_BRANCH != 'master'
  additional_containers:
    - image: node:latest
  # Clean workspace:
  CleanWorkspace_script:
    - make clean
  # Install test dependencies:
  InstallTestDependencies_script:
    - make testrequirements
    - make devrequirements
  # Build the package:
  BuildPackage_script:
    - make dist
  # Install new beta build:
  InstallBetaBuild_script:
    - make beta
  # Test the code:
  RunTests_script:
    - make test
  PyDocStyle_script:
    - make pydocstyle
  PyCodeStyle_script:
    - make pycodestyle
  Flake8Style_script:
    - make flake8
  PylintStyle_script:
    - make pylint
  DependencySecurityTest_script:
    - make safetyci
  InstallLinuxbrew_script:
    - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  InstallNodeJS_script:
    - brew install node
  # Install Markdown linter:
  InstallLinter_script:
    - make installmdlint
  # Install Markdown link checker:
  InstallLinkChecker_script:
    - make installlinkcheck
  # Lint Markdown:
  MarkdownLint_script:
    - find . -name '*.md' -exec markdownlint --config=.markdownlint.yml {} \;
  # Check links:
  LinkCheck_script:
    - make linkcheck
