task:
  name: Continuous Integration
  container:
    image: python:latest
  only_if: $CIRRUS_BRANCH != 'python-2-supported'
  use_compute_credits: $CIRRUS_BRANCH == 'master' || $CIRRUS_TAG != ''
  auto_cancellation: true
  Python_cache:
    folder: /usr/local/lib/python3.7/site-packages
    populate_script:
      - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/test.txt
  Install_Beta_Build_script:
    - python3 -m pip install .
  Run_Python_Tests_script:
    - export TARGET=code
    - python3 code_tests.py

Deploy_task:
  container:
    image: python:latest
  env:
    TWINE_USERNAME: ENCRYPTED[174042b48782072dfd0c112ac176d000b1f4753424d0781a7d5a9fb8a50f14cdf54b2fa9b340ba1c5c4cb017a979d956]
    TWINE_PASSWORD: ENCRYPTED[00e22066a3e9d3cfde8533ab01441d876b42ec46e80a1c673c46b94f771728d6aac8382d0f1b8366fb3261fd3145ed58]
  only_if: $CIRRUS_TAG != ''
  auto_cancellation: false
  use_compute_credits: true
  depends_on:
    - Continuous Integration
    - Documentation Tests
  Install_Requirements_script:
    - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/test.txt
  Build_script:
    - make dist
  script:
    - twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD dist/*

task:
  name: Markdown Tests
  container:
    image: node:latest
  use_compute_credits: $CIRRUS_TAG != ""
  auto_cancellation: true
  Install_script:
    - npm install -g markdown-link-check@3.7.2
    - npm install -g markdownlint-cli@0.14.0
    - npm install -g markdown-spellcheck@0.11.0
  script:
    - find . -name \*.md -exec markdown-link-check {} \;
    - find . -name \*.md -exec markdownlint --config=.markdownlint.yml {} \;
    - mdspell '**/*.md' '!CODE_OF_CONDUCT.md' '!.github/CODEAUTHORS.md' '!extras/*.md' --ignore-numbers --ignore-acronyms --report --en-us;

task:
  name: Dependency Safety Tests
  container:
    image: python:latest
  use_compute_credits: $CIRRUS_TAG != ""
  auto_cancellation: true
  Python_cache:
    folder: /usr/local/lib/python3.7/site-packages
    populate_script:
      - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/test.txt
  script:
    - export TARGET=safety
    - python3 code_tests.py

task:
  name: reStructuredText Linting Tests
  container:
    image: python:latest
  use_compute_credits: $CIRRUS_TAG != ""
  auto_cancellation: true
  Python_cache:
    folder: /usr/local/lib/python3.7/site-packages
    populate_script:
      - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/test.txt
  script:
    - export TARGET=rst
    - python3 code_tests.py

task:
  name: Documentation Tests
  container:
    image: python:latest
  use_compute_credits: true
  auto_cancellation: true
  Download_Sphinx_script:
    - python3 -m pip install --upgrade -r $CIRRUS_WORKING_DIR/requirements/docs.txt
  script:
    - cd ./docs/
    - make html
