osx_instance:
  image: mojave-xcode-10.1

Tests_task:
  only_if: $CIRRUS_BRANCH != 'python-2-supported'
  auto_cancellation: $CIRRUS_BRANCH != 'master'
  # Clean workspace:
  InstallNodeJS_script:
    - brew install node
  InstallPython_script:
    - brew install python@3
  CleanWorkspace_script:
    - make clean
  # Install test dependencies:
  InstallTestDependencies_script:
    - make testrequirements
    - make devrequirements
  # Build the package:
  BuildPackage_script:
    - make dist
  # Install new beta build:
  InstallBetaBuild_script:
    - make beta
  # Test the code:
  RunTests_script:
    - make test
  PyDocStyle_script:
    - make pydocstyle
  PyCodeStyle_script:
    - make pycodestyle
  Flake8Style_script:
    - make flake8
  PylintStyle_script:
    - make pylint
  DependencySecurityTest_script:
    - make safetyci
  # Install Markdown linter:
  InstallLinter_script:
    - make installmdlint
  # Install Markdown link checker:
  InstallLinkChecker_script:
    - make installlinkcheck
  # Lint Markdown:
  MarkdownLint_script:
    - find . -name '*.md' -exec markdownlint --config=.markdownlint.yml {} \;
  # Check links:
  LinkCheck_script:
    - make linkcheck
