task:
  container:
    image: python:latest
  use_compute_credits: true
  auto_cancellation: true
  Python_cache:
    folder: /usr/local/lib/python3.7/site-packages
    fingerprint_script:
      - echo $CI
      - echo $OS
      - echo $CIRRUS_SHELL
      - find ./requirements/ -name \*.txt -exec cat {} \;
    populate_script: find ./requirements/ -name \*.txt -exec python3 -m pip install --upgrade -r {} \;
  Install_Beta_Build_script:
    - python3 -m pip install .
  matrix:
    - env:
        TARGET: code
      name: Code Tests
      only_if: $CIRRUS_BRANCH != 'python-2-supported'
      script: python3 code_tests.py
    - env:
        TARGET: rst
      name: reStructuredText Tests
      script: python3 code_tests.py
    - env:
        TARGET: pull_request
      only_if: $CIRRUS_PR != ''
      script: python3 code_tests.py
      name: Pull Request Validator
    - env:
        TARGET: safety
      name: Test Dependencies
      script: python3 code_tests.py
    - env:
        TARGET: sphinxdocs
      script: python3 -m pip install -r requirements/docs.txt && cd ./docs/ && make html && rm -rf _build
      name: Documentation Tests
    - env:
        TARGET: description
      script: python3 setup.py sdist bdist_wheel && python3 -m twine check dist/*
      name: Description Validation
    - env:
        TARGET: deploy
        TWINE_USERNAME: ENCRYPTED[174042b48782072dfd0c112ac176d000b1f4753424d0781a7d5a9fb8a50f14cdf54b2fa9b340ba1c5c4cb017a979d956]
        TWINE_PASSWORD: ENCRYPTED[00e22066a3e9d3cfde8533ab01441d876b42ec46e80a1c673c46b94f771728d6aac8382d0f1b8366fb3261fd3145ed58]
      name: Deploy
      only_if: $CIRRUS_TAG != ''
      depends_on:
        - Code Tests
        - Documentation Tests
      script: make dist && python3 -m twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD dist/*

task:
  matrix:
    - name: Markdown Tests
      container:
        image: node:latest
      Install_script:
        - npm install -g markdownlint-cli@0.14.0
        - npm install -g markdown-spellcheck@0.11.0
      script:
        - find . -name \*.md -exec markdownlint --config=.markdownlint.yml {} \;
        - mdspell '**/*.md' '!CODE_OF_CONDUCT.md' '!.github/CODEAUTHORS.md' --ignore-numbers --ignore-acronyms --report --en-us;
    - name: Markdown Link Checking
      container:
        image: jumbocakeyumyum/mdlink:latest
      script:
        - find . -name \*.md -exec markdown-link-check {} \;
  use_compute_credits: true
  auto_cancellation: true
