osx_instance:
  image: mojave-xcode-10.1

Tests_task:
  # Don't run on Python2 branch:
  only_if: $CIRRUS_BRANCH != 'python-2-supported'
  # Do not skip if new commits are pushed to master:
  auto_cancellation: $CIRRUS_BRANCH != 'master'

  # Install Python3 and NodeJS:
  InstallNodeJS_script:
    - brew install node
  InstallPython_script:
    - brew install python@3

  # Clean workspace:
  CleanWorkspace_script:
    - make clean

  # Install test dependencies:
  InstallTestDependencies_script:
    - make testrequirements
    - make devrequirements

  # Build the package:
  BuildPackage_script:
    - make dist

  # Install new beta build:
  InstallBetaBuild_script:
    - make beta

  # Test the Python code:
  RunTests_script:
    - make test

  # Run Python linting:
  PyDocStyle_script:
    - make pydocstyle
  PyCodeStyle_script:
    - make pycodestyle
  Flake8Style_script:
    - make flake8
  PylintStyle_script:
    - make pylint

  # Test dependencies for security issues:
  DependencySecurityTest_script:
    - make safetyci

  # Install Markdown linter:
  InstallLinter_script:
    - make installmdlint

  # Install Markdown link checker:
  InstallLinkChecker_script:
    - make installlinkcheck

  # Lint Markdown:
  MarkdownLint_script:
    - find . -name '*.md' -exec markdownlint --config=.markdownlint.yml {} \;

  # Check links in markdown:
  LinkCheck_script:
    - make linkcheck
