container:
  image: python:latest

MarkdownTests_task:
  container:
    image: node:latest
  # Install Markdown linter:
  InstallLinter_script: npm install -g markdownlint-cli
  # Install Markdown link checker:
  InstallLinkChecker_script: npm install -g markdown-link-check@3.7.2
  # Lint Markdown:
  MarkdownLint_script:
    - markdownlint --config=.markdownlint.yml *.md
    - markdownlint --config=.markdownlint.yml .github/*.md
    - markdownlint --config=.markdownlint.yml .github/ISSUE_TEMPLATE/*.md
    - markdownlint --config=.markdownlint.yml extras/*.md
  # Check links:
  LinkCheck_script: find . -name \*.md -exec markdown-link-check {} \;

task:
  name: CodeTests
  only_if: $CIRRUS_BRANCH != 'python-2-supported'
  auto_cancellation: $CIRRUS_BRANCH != 'master'
  # Install test dependencies:
  InstallTestDependencies_script:
    - python3 -m pip install -r requirements/test.txt
  # Build the package:
  BuildPackage_script:
    - make dist
  # Install new beta build:
  InstallBetaBuild_script:
    - python3 -m pip install .
  # Test the code:
  RunTests_script:
    - make test
