container:
  image: python:latest

MarkdownTests_task:
  container:
    image: node:latest
  InstallLinter_script: npm install -g markdownlint-cli
  InstallLinkChecker_script: npm install -g markdown-link-check@3.7.2
  MarkdownLint_script:
    - markdownlint --config=.markdownlint.yml *.md
    - markdownlint --config=.markdownlint.yml .github/*.md
    - markdownlint --config=.markdownlint.yml extras/*.md
  LinkCheck_script: find . -name \*.md -exec markdown-link-check {} \;

CodeTests_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements/test.txt
    populate_script: python3 -m pip install -r requirements/test.txt
  InstallTestDependencies_script:
    - python3 -m pip install --upgrade area4
  Test_script:
    - python3 test-code.py
