test_task:
  container:
    image: python:latest
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cd requirements/ cat test.txt
    populate_script: python3 -m pip install --upgrade pip==9.0.1 && python3 -m pip install --upgrade setuptools wheel twine
  test_script: python3 setup.py sdist bdist_wheel && rm -r build/ && ls dist/

link_check_task:
  container:
    image: node:latest
  depends_on:
    - test
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat requirements.txt
    populate_script: npm install -g markdown-link-check@3.7.2
  script: find . -name \*.md -exec markdown-link-check {} \;

markdown_lint_task:
  container:
    image: node:latest
  depends_on:
    - test
    - link_check
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat requirements.txt
    populate_script: npm install -g remark-lint remark-cli remark-preset-lint-recommended
  script: find . -name \*.md -exec remark {} \;
