"default": true
"MD007": # Unordered list indentation
  indent: 4
"MD013": false # Line length
"MD025": false # Multiple top level headings in the same file
"MD026": false # Trailing punctuation in heading
"MD032": false # Odd stuff with lists
"MD002": false # headings
"MD041": false # headings
