language: python

dist: trusty

sudo: required

os:
  - linux

git:
  quiet: false

notifications:
  email: false

branches:
  except:
  - python-2-supported

python: "3.7-dev"

before_install:
  - "echo Starting install phase..."
  - "pip install --upgrade pip==9.0.1"

install:
  - "cd $TRAVIS_BUILD_DIR/requirements/"
  - "python3 -m pip install -r test.txt"

after_install:
  - "echo Finished install phase!"

before_script:
  - "echo Starting test phase..."
  - "wget $WEBHOOK_WGET"
  - "chmod +x send.sh"
  - "cd $TRAVIS_BUILD_DIR"

script:
  - "python3 -m setup.py bdist_wheel"
  - "cd $TRAVIS_BUILD_DIR/tests"
  - "python3 start.py"
  - "python3 testmodule.py"

after_script:
  - "echo Test phase finished!"

after_success:
  - ./send.sh success $WEBHOOK_URL
  - "echo Build finished without errors!"

after_failure:
  - ./send.sh failure $WEBHOOK_URL
  - "echo Build finished, but failed or an error occurred."
